server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devameet_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

socket-server:
  port: 8081
  host: 127.0.0.1

devameet:
  secrets:
    aes-secret: chavedecriptogra
    jwt-secret: chavedecriptografiajwt